### PR TITLE
Added translations

### PR DESCRIPTION
**Pull request by Armandur**
Added dashboard.txt translations

### CODE REVIEW

**Comment by spencerjunraid** [comment]
Thank you!

**Comment by spencerjunraid** [comment]
Are you muppie on the forums?

**Comment by muppie** [comment]
Hi,
Yes

**Comment by Armandur** [comment]
I am not Muppie I just found the repo via reddit :)

**Comment by spencerjunraid** [comment]
@Armandur - Oh excellent. Thank you very much! Do you have an Unraid forum handle?

**Comment by Armandur** [comment]
@spencerjunraid it is Armandur there as well.

**Pull request merged**
